meta_product_name: "WROND!"
meta_title: "WROND! - Learn Kanji - The Fun Way!"
meta_description: "Learn to read kannji via fun and engaging number puzzles!"
meta_image: "WROND.png" # should exist in `app/assets/images/`
